// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public static class NotAvailable
    {
        public const double Numeric = 9999999999999999d;
        public const double LongDouble = -1L;
        public const string Text = "N/A";
        public const string DateTime = "";
    }

    public static class DataMinerValue
    {
        public static object Resolve(double? value) =>
            value.HasValue ? (object)value.Value : NotAvailable.Numeric;

        public static object ResolveLongDouble(double? value) =>
            value.HasValue ? (object)value.Value : NotAvailable.LongDouble;

        public static object Resolve(string value) =>
            string.IsNullOrEmpty(value) ? NotAvailable.Text : value;

        public static object Resolve(DateTimeOffset? value, string format = "yyyy-MM-dd HH:mm:ss") =>
            value.HasValue ? (object)value.Value.ToString(format) : NotAvailable.DateTime;
    }

    public partial class Welcome
    {
        [JsonProperty("status")]
        public Status Status { get; set; }

        [JsonProperty("data")]
        public Datum[] Data { get; set; }

        public static Welcome FromJson(string json) =>
            JsonConvert.DeserializeObject<Welcome>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Welcome self) =>
            JsonConvert.SerializeObject(self, Converter.Settings);
    }

    public partial class Datum
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("symbol")]
        public string Symbol { get; set; }

        [JsonProperty("slug")]
        public string Slug { get; set; }

        [JsonProperty("num_market_pairs")]
        public long NumMarketPairs { get; set; }

        [JsonProperty("date_added")]
        public DateTimeOffset DateAdded { get; set; }

        [JsonProperty("tags")]
        public string[] Tags { get; set; }

        [JsonProperty("max_supply")]
        public double? MaxSupply { get; set; }

        [JsonProperty("circulating_supply")]
        public double CirculatingSupply { get; set; }

        [JsonProperty("total_supply")]
        public double TotalSupply { get; set; }

        [JsonProperty("infinite_supply")]
        public bool InfiniteSupply { get; set; }

        [JsonProperty("platform")]
        public Platform Platform { get; set; }

        [JsonProperty("cmc_rank")]
        public long CmcRank { get; set; }

        [JsonProperty("self_reported_circulating_supply")]
        public double? SelfReportedCirculatingSupply { get; set; }

        [JsonProperty("self_reported_market_cap")]
        public double? SelfReportedMarketCap { get; set; }

        [JsonProperty("tvl_ratio")]
        public double? TvlRatio { get; set; }

        [JsonProperty("last_updated")]
        public DateTimeOffset LastUpdated { get; set; }

        [JsonProperty("quote")]
        public Quote Quote { get; set; }
    }

    public partial class Platform
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("symbol")]
        public string Symbol { get; set; }

        [JsonProperty("slug")]
        public string Slug { get; set; }

        [JsonProperty("token_address")]
        public string TokenAddress { get; set; }
    }

    public partial class Quote
    {
        [JsonProperty("USD")]
        public Usd Usd { get; set; }
    }

    public partial class Usd
    {
        [JsonProperty("price")]
        public double Price { get; set; }

        [JsonProperty("volume_24h")]
        public double Volume24H { get; set; }

        [JsonProperty("volume_change_24h")]
        public double VolumeChange24H { get; set; }

        [JsonProperty("percent_change_1h")]
        public double PercentChange1H { get; set; }

        [JsonProperty("percent_change_24h")]
        public double PercentChange24H { get; set; }

        [JsonProperty("percent_change_7d")]
        public double PercentChange7D { get; set; }

        [JsonProperty("percent_change_30d")]
        public double PercentChange30D { get; set; }

        [JsonProperty("percent_change_60d")]
        public double PercentChange60D { get; set; }

        [JsonProperty("percent_change_90d")]
        public double PercentChange90D { get; set; }

        [JsonProperty("market_cap")]
        public double MarketCap { get; set; }

        [JsonProperty("market_cap_dominance")]
        public double MarketCapDominance { get; set; }

        [JsonProperty("fully_diluted_market_cap")]
        public double FullyDilutedMarketCap { get; set; }

        [JsonProperty("tvl")]
        public double? Tvl { get; set; }

        [JsonProperty("last_updated")]
        public DateTimeOffset LastUpdated { get; set; }
    }

    public partial class Status
    {
        [JsonProperty("timestamp")]
        public DateTimeOffset Timestamp { get; set; }

        [JsonProperty("error_code")]
        public long ErrorCode { get; set; }

        [JsonProperty("error_message")]
        public object ErrorMessage { get; set; }

        [JsonProperty("elapsed")]
        public long Elapsed { get; set; }

        [JsonProperty("credit_count")]
        public long CreditCount { get; set; }

        [JsonProperty("notice")]
        public object Notice { get; set; }

        [JsonProperty("total_count")]
        public long TotalCount { get; set; }
    }

    public partial class GlobalQuotesResponse
    {
        [JsonProperty("data")]
        public GlobalQuotesData Data { get; set; }

        public static GlobalQuotesResponse FromJson(string json) =>
            JsonConvert.DeserializeObject<GlobalQuotesResponse>(json, Converter.Settings);
    }

    public partial class GlobalQuotesData
    {
        [JsonProperty("active_cryptocurrencies")]
        public long ActiveCryptocurrencies { get; set; }

        [JsonProperty("total_cryptocurrencies")]
        public long TotalCryptocurrencies { get; set; }

        [JsonProperty("active_market_pairs")]
        public long ActiveMarketPairs { get; set; }

        [JsonProperty("active_exchanges")]
        public long ActiveExchanges { get; set; }

        [JsonProperty("total_exchanges")]
        public long TotalExchanges { get; set; }

        [JsonProperty("btc_dominance")]
        public double BtcDominance { get; set; }

        [JsonProperty("eth_dominance")]
        public double EthDominance { get; set; }

        [JsonProperty("btc_dominance_yesterday")]
        public double BtcDominanceYesterday { get; set; }

        [JsonProperty("eth_dominance_yesterday")]
        public double EthDominanceYesterday { get; set; }

        [JsonProperty("btc_dominance_24h_percentage_change")]
        public double BtcDominance24hPercentageChange { get; set; }

        [JsonProperty("eth_dominance_24h_percentage_change")]
        public double EthDominance24hPercentageChange { get; set; }

        [JsonProperty("defi_volume_24h")]
        public double DefiVolume24h { get; set; }

        [JsonProperty("defi_market_cap")]
        public double DefiMarketCap { get; set; }

        [JsonProperty("defi_24h_percentage_change")]
        public double Defi24hPercentageChange { get; set; }

        [JsonProperty("stablecoin_volume_24h")]
        public double StablecoinVolume24h { get; set; }

        [JsonProperty("stablecoin_market_cap")]
        public double StablecoinMarketCap { get; set; }

        [JsonProperty("stablecoin_24h_percentage_change")]
        public double Stablecoin24hPercentageChange { get; set; }

        [JsonProperty("derivatives_volume_24h")]
        public double DerivativesVolume24h { get; set; }

        [JsonProperty("derivatives_24h_percentage_change")]
        public double Derivatives24hPercentageChange { get; set; }

        [JsonProperty("quote")]
        public GlobalQuote Quote { get; set; }

        [JsonProperty("last_updated")]
        public DateTimeOffset LastUpdated { get; set; }
    }

    public partial class GlobalQuote
    {
        [JsonProperty("USD")]
        public GlobalUsd Usd { get; set; }
    }

    public partial class GlobalUsd
    {
        [JsonProperty("total_market_cap")]
        public double TotalMarketCap { get; set; }

        [JsonProperty("total_volume_24h")]
        public double TotalVolume24H { get; set; }

        [JsonProperty("total_volume_24h_reported")]
        public double TotalVolume24hReported { get; set; }

        [JsonProperty("altcoin_volume_24h")]
        public double AltcoinVolume24h { get; set; }

        [JsonProperty("altcoin_market_cap")]
        public double AltcoinMarketCap { get; set; }

        [JsonProperty("defi_volume_24h")]
        public double DefiVolume24h { get; set; }

        [JsonProperty("defi_market_cap")]
        public double DefiMarketCap { get; set; }

        [JsonProperty("defi_24h_percentage_change")]
        public double Defi24hPercentageChange { get; set; }

        [JsonProperty("stablecoin_volume_24h")]
        public double StablecoinVolume24h { get; set; }

        [JsonProperty("stablecoin_market_cap")]
        public double StablecoinMarketCap { get; set; }

        [JsonProperty("stablecoin_24h_percentage_change")]
        public double Stablecoin24hPercentageChange { get; set; }

        [JsonProperty("derivatives_volume_24h")]
        public double DerivativesVolume24h { get; set; }

        [JsonProperty("derivatives_24h_percentage_change")]
        public double Derivatives24hPercentageChange { get; set; }

        [JsonProperty("total_market_cap_yesterday")]
        public double TotalMarketCapYesterday { get; set; }

        [JsonProperty("total_volume_24h_yesterday")]
        public double TotalVolume24hYesterday { get; set; }

        [JsonProperty("total_market_cap_yesterday_percentage_change")]
        public double TotalMarketCapYesterdayPercentageChange { get; set; }

        [JsonProperty("total_volume_24h_yesterday_percentage_change")]
        public double TotalVolume24hYesterdayPercentageChange { get; set; }

        [JsonProperty("last_updated")]
        public DateTimeOffset LastUpdated { get; set; }
    }

    public partial class CategoriesResponse
    {
        [JsonProperty("data")]
        public CategoryItem[] Data { get; set; }

        public static CategoriesResponse FromJson(string json) =>
            JsonConvert.DeserializeObject<CategoriesResponse>(json, Converter.Settings);
    }

    public partial class CategoryItem
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("num_tokens")]
        public double NumTokens { get; set; }

        [JsonProperty("num_coins")]
        public double NumCoins { get; set; }

        [JsonProperty("market_cap")]
        public double MarketCap { get; set; }

        [JsonProperty("market_cap_change")]
        public double MarketCapChange { get; set; }

        [JsonProperty("volume")]
        public double Volume { get; set; }

        [JsonProperty("last_updated")]
        public string LastUpdated { get; set; }

        [JsonProperty("avg_price_change")]
        public double AvgPriceChange { get; set; }

        [JsonProperty("volume_change")]
        public double VolumeChange { get; set; }
    }

    public partial class CategoryDetailResponse
    {
        [JsonProperty("data")]
        public CategoryItem Data { get; set; }

        public static CategoryDetailResponse FromJson(string json) =>
            JsonConvert.DeserializeObject<CategoryDetailResponse>(json, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}